//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminInfo
    {
        public int AdminID { get; set; }
        public string AdminName { get; set; }
        public string admin_email { get; set; }
        public string mobile { get; set; }
        public string password { get; set; }
    }
}
